/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CharacterCammyRouteImport } from './routes/character/cammy'
import { Route as CharacterAkiRouteImport } from './routes/character/aki'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharacterCammyRoute = CharacterCammyRouteImport.update({
  id: '/character/cammy',
  path: '/character/cammy',
  getParentRoute: () => rootRouteImport,
} as any)
const CharacterAkiRoute = CharacterAkiRouteImport.update({
  id: '/character/aki',
  path: '/character/aki',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/signup': typeof SignupRoute
  '/character/aki': typeof CharacterAkiRoute
  '/character/cammy': typeof CharacterCammyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/signup': typeof SignupRoute
  '/character/aki': typeof CharacterAkiRoute
  '/character/cammy': typeof CharacterCammyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/signup': typeof SignupRoute
  '/character/aki': typeof CharacterAkiRoute
  '/character/cammy': typeof CharacterCammyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/home'
    | '/signup'
    | '/character/aki'
    | '/character/cammy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/home'
    | '/signup'
    | '/character/aki'
    | '/character/cammy'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/home'
    | '/signup'
    | '/character/aki'
    | '/character/cammy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  HomeRoute: typeof HomeRoute
  SignupRoute: typeof SignupRoute
  CharacterAkiRoute: typeof CharacterAkiRoute
  CharacterCammyRoute: typeof CharacterCammyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/character/cammy': {
      id: '/character/cammy'
      path: '/character/cammy'
      fullPath: '/character/cammy'
      preLoaderRoute: typeof CharacterCammyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/character/aki': {
      id: '/character/aki'
      path: '/character/aki'
      fullPath: '/character/aki'
      preLoaderRoute: typeof CharacterAkiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  HomeRoute: HomeRoute,
  SignupRoute: SignupRoute,
  CharacterAkiRoute: CharacterAkiRoute,
  CharacterCammyRoute: CharacterCammyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
